CC     = x86_64-w64-mingw32-gcc
CFLAGS = -std=c99 -Wall -Wextra -g3 -O3 -DNDEBUG
LDLIBS = -lm

gcom.exe : main.c display.c map.c game.c rand.c device_mingw.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

clean :
	$(RM) gcom gcom.exe *.o
