CC     = x86_64-w64-mingw32-gcc
LD     = x86_64-w64-mingw32-ld
CFLAGS = -std=c99 -Wall -Wextra -g3 -O3 -DNDEBUG
LDLIBS = -lm

sources := main.c display.c map.c game.c rand.c device_mingw.c

gcom.exe : doc/story.o $(addprefix src/,$(sources))
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

clean :
	$(RM) persist.gcom gcom gcom.exe doc/*.o

%.o : %.txt
	$(LD) -r -b binary -o $@ $<
